### ISSUE TITLE
missing mat{1,2}.txt and golden{1,2,3}.txt

### ISSUE THREAD

**Issue by knownothing8** [abdelazeem201/Systolic-array-implementation-in-RTL-for-TPU#1]
in test_tpu.v, cannot find following files for simulation.  Can you upload those files in github? 

    $readmemb("data/mat1.txt", mat1);
    $readmemb("data/mat2.txt", mat2);
    $readmemb("golden/golden1.txt",golden1);
    $readmemb("golden/golden2.txt",golden2);
    $readmemb("golden/golden3.txt",golden3);

**Comment by abdelazeem201** [comment]
I uploaded them in [Pre-Synthesis_Simulation](https://github.com/abdelazeem201/Systolic-array-implementation-in-RTL-for-TPU/tree/main/Pre-Synthesis_Simulation)
